### ISSUE TITLE
Undefined index: status in restful_token_auth_user_update()

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#209]
It doesn't happen every time I log into beta, but on multiple occasions I've gotten the error 

"Notice: Undefined index: status in restful_token_auth_user_update() (line 134 of /var/www/html/beta.bugguide.net/bugguide/sites/all/modules/restful/modules/restful_token_auth/restful_token_auth.module)."

when I login:
![login_error](https://user-images.githubusercontent.com/632915/124466314-29073500-dd5c-11eb-8a82-392f10bef64a.jpg)

**Comment by clouseau** [comment]
Yes, this is an annoyance. restful\_token\_auth\_user\_update() should be checking for the existence of status in [https://github.com/bugguide/bugguide/blob/9b2510bcd0e3f37f724a0419d7d4f322771c8e24/sites/all/modules/restful/modules/restful_token_auth/restful_token_auth.module#L134](https://github.com/bugguide/bugguide/blob/9b2510bcd0e3f37f724a0419d7d4f322771c8e24/sites/all/modules/restful/modules/restful_token_auth/restful_token_auth.module#L134) before testing it.

In a perfect world this would be fixed in the module. However, we will turn off notices in production.

**Comment by clouseau** [comment]
OK, I am sufficiently annoyed by this now that I have made a commit.
