### ISSUE TITLE
Comments on some pages are set to Preview Required

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#219]
Guide pages and Image pages are set to Comment Preview Required, so that the user is required to preview a comment before it can be saved. I'm not sure if that was intentional or not, please close if it was.

**Comment by kleintom** [comment]
(And just now I see that comments for guide pages aren't showing up because, even though comments are enabled for guide pages, the comments field is disabled in "Manage Display", so the comments section would work if it was displayed, but it's not displayed.)

**Comment by clouseau** [comment]
I think comments should be disabled for Guide Pages, just like current BugGuide. Improvements are handled through the Guide Page Improvement forum. Otherwise Guide Pages are going to become very messy.

I believe comments are not editable, so I think that requiring preview is reasonable. We do not currently require it though.

**Comment by clouseau** [comment]
Ah. I see they are editable, under certain conditions.

  \*\* Authenticated users can edit their comments as long they have  
  \*\* not been replied to.  This, in order to avoid people changing  
  \*\* or revising their statements based on the replies their posts  
  \*\* got. Furthermore, users can't reply to their own comments and  
  \*\* are encouraged to extend their original comment.

**Comment by kleintom** [comment]
You can now save a comment directly without preview on an image on beta, closing as fixed.
