### ISSUE TITLE
Getting "413 Request Entity Too Large" on a 1.6M image

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#230]
Attempted to upload this image: https://bugguide.net/images/raw/MRY/ZER/MRYZERJZIRCZIRJZQRWLMZDLHZFZ3LUL3LPLQRTZSRULYL2L0RPLHZJZFLULFL9LHZPLKZHHKZ1LPRRH.jpg three times to Id Request in beta, each time got a "413 Request Entity Too Large" error page, even though the image is 1.6M and the submission rule says "Files must be less than 2 MB.".

**Comment by clouseau** [comment]
Please try again. The nginx reverse proxy was set to its default of 1MB for client\_max\_body\_size which was artificially limiting the upload.

Upload size on current BugGuide is set to 3MB, I believe. I've matched that on beta, but we should probably have a discussion soon because I am getting complaints from people who want to upload massive images from their iPhone and do not want to resize them.

**Comment by kleintom** [comment]
Looks like it's working now: I was able to upload what my file browser called a 2.9 and a 3.1 MB file, but not a 3.9MB file, which gave the following useful error:
![3 9](https://user-images.githubusercontent.com/632915/126882725-481ac1cd-56ed-40b8-8d90-3113d0cddb20.jpg)
Thanks!
