### ISSUE TITLE
'Representative of Taxon' and 'Photographic Quality' question

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#263]
This is a question that may or may not become an issue - please close if there's nothing to do here.

![rep](https://user-images.githubusercontent.com/632915/128583051-c45dff00-f704-4514-9f20-3eb85f44ea97.jpg)
If I'm logged in as 'authenticated' I see the 'Representative of Taxon' and 'Photographic Quality' ratings - am I supposed to? As a non-editor, personally I wouldn't want to vote on 'Representative of Taxon' since I don't have that expertise (as an added wrinkle you can't clear your vote once you've voted, so if you try it out to see what happens (or just misclick), it's going to stick); are we giving all users the vote to determine which images are representative of a taxon?
Image quality seems more like something anybody could vote on, but I could also see making that an editor/expert-only decision as well.

**Comment by kleintom** [comment]
(Also thinking it would probably be nice for editors to have self-updating fields like these for things like sex and life stage (especially with an 'apply to all in series' option) right on the image page - one less loading page to wait for to set/change them.)

**Comment by clouseau** [comment]
On current BugGuide anyone uploading an image can mark it Representative. Unfortunately this box has always been checked by default, so I suspect that many new to BugGuide don't know what it means and leave it checked.

Of 1730442 images on BugGuide this morning, 1625575 (94%) are marked representative. No way is that true.

So our permission options for who can mark an image representative:

Editors? Yes, definitely.

If it's my image? Maybe. If I know what it is. No real way of telling whether the author knows. I lean toward yes; just don't rank it if you don't know whether it's representative of the taxon.

If I'm an authenticated user? I lean toward yes here too, since we have lots of people who are not editors but have expertise.

Another option is to build another role called ranker or something. Or use gamification to provide the role after you've submitted x number of images. Lots of options here.

If I'm an anonymous user? No. You must be logged in to vote.

I feel like crowdsourcing will autocorrect and bring representative images to the top. Editors can always manually specify representative images on a guide page (once #279 is fixed). It's certainly an improvement over today, where 94% of images are marked representative.

But to the immediate concerns: no way to unvote. See also #58.

**Comment by kleintom** [comment]
When I'm logged into current bugguide I don't see a Representative checkbox when submitting a new image, I don't recall ever seeing one.  That might explain the 94%! :-)

I haven't been through these parts of the code yet, so feel free to only respond if you think it's worth writing it out in an issue, but it's not clear to me how the Representative checkbox, the "Representative of Taxon" five star, and the "Photographic Quality" five star are going to be used/combined.
* As far as I can tell there's no Representative checkbox currently exposed in beta's image submission form, neither for authenticated nor admin users; is there currently no way to change that after migration or set/change it on new images?
* There's now the Representative boolean(?) that is being migrated, and in addition on beta there are the two five star voting fields.
  * In #279 the code block you reference it looks like it's only checking the migrated field_representative_images field in order to decide which images to show on a guide page - so the representative_images field is only used to filter out which images are shown at the top of a guide page (i.e. an Info tab page)?
  * I see an average representative rating and a representative rating count are being used to sort images being displayed for a given taxon at https://github.com/bugguide/bugguide/blob/6748313e368d854d0b6646ce37874c873d8aa4f1/sites/all/modules/custom/bgpage/bgpage.ds.field.inc#L156-L157 - I think those are the images that appear on the Images tab, right?
  * I could easily be missing it, but I'm not seeing the Photographic Quality ratings being used anywhere right now?

With my current superficial understanding of things, I wonder if it would be confusing for users to have two ways to mark an image as "Representative" - one simply 'yes' or 'no', the other a 1-5 scale? I feel like it wouldn't be clear how either/all of those fields are being used (maybe the Representative checkbox comes with an explanation?).

**Comment by kleintom** [comment]
Honest, but maybe not helpful, question: is it meaningful to say an image is representative of a Family? an Order? If an image is marked highly representative of a family, and then years later gets IDed to species, is it still necessarily highly representative of that species?

**Comment by kleintom** [comment]
Oh, sorry, rereading issue 279, I see that the Representative Images being discussed there is only set by editors on a Guide page, not on individual images, and that that field does still show up on guide pages on beta (if you have the right permission).

**Comment by kleintom** [comment]
But then in your previous comment you mention "On current BugGuide anyone uploading an image can mark it Representative." - so is there _another_ representative boolean on current bugguide for individual images? Is that being replaced by the representative five star on beta? or is it being migrated and combined with the five star somehow?  Apologies for all the questions...

**Comment by clouseau** [comment]
Sorry for the confusion. There is plenty to go around! There are several compounding issues that come to rest in these fields.

The Representative Images field on the Guide page is unchanged. This is a text field which may be blank, or may contain comma-delimited nids that an editor can place after hand-picking the best representatives for a taxon. Order and number of images should be respected here. This is #279. Currently 344 bgpages have a hand-picked set, 53,297 do not.

On current BugGuide, there is a boolean checkbox for bgimage that indicates that an image is representative of a taxon. If an editor has not specified a manual set, BugGuide randomly selects 8 images that have been marked representative.

Unfortunately as the representative checkbox defaults to on, this is not useful. The set of 94% checked checkboxes is not being migrated. What replaces it? The fivestar ranking of whether or not this image is representative of a taxon replaces it. That way images that show the particular identifying marks for a taxon can be ranked high. The ranking gives more control than a boolean by allowing someone to say not only that is it representative but how representative it is.

You ask a good question about whether an image is representative at a species level, family level, etc. To this I do not have a good answer other than to say, this problem is no different than it was in the previous system.

Regarding the Photographic Quality ranking, this replaces Frass which has been extremely controversial and troublesome. Instead of "frassing" an image, it gets marked 1 star in quality. My original vision was to be able to browse BugGuide with various filters in place, such as "show me only images that have been marked 3 stars or higher in quality" which at once solves the problem of people who say "we need this blurry but rare dragonfly as a data point" and those who say "the Guide should not show awful blurry or far-away images". We still need a solution for "can't identify, ever" but now I am getting off topic.

**Comment by kleintom** [comment]
Thanks for the great explanation, that was very helpful. I'm going to close this issue for now since it sounds like what we're currently doing is in line with what you're thinking.

**Comment by Entomike** [comment]
not sure I have absorbed everything above, but...
I think photo quality and representative images should be core concerns of BG 1, 2, 3 etc.
1) will BG2 allow for **larger images**?
2a) thinking out loud here, might past and new images (not deselected as representative) be assigned a 3 or 4 score until they are voted up to a 5? (otherwise a lot of **down voting** has to happen (particularly for common spp.) vs. less **up voting** to get the cream to rise to the top.)
2b) I sincerely hope that image voting will be one click vs. 3 or 4 clicks that are currently required...
3) what about having additional photo (sub?) categories such as **ventral, lateral, headshot** that would facilitate examining features that may be diagnostic in those views?
4) what about making the **Immature** category work for taxa beyond Leps??

**Comment by Entomike** [comment]
Re: designating shots as ventral, lateral, etc, it might not be too much of a burden if it was one click and if it was optional. 

Re: clicking bubbles, I would prefer a slightly larger bubble than those below the photos (and elsewhere) in BG1.
