### ISSUE TITLE
Manual representative images not showing

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#279]
Now that data for representative images that have manually been selected by editors in the Representative Images field of guide pages is making it through migration, I'm opening this issue because they don't actually get displayed in the area at the top of the guide page.

Example: [https://beta.bugguide.net/node/1954](https://beta.bugguide.net/node/1954)

Compare: [https://bugguide.net/node/view/1954](https://bugguide.net/node/view/1954)

#160 is related.

Relevant code:

https://github.com/bugguide/bugguide/blob/b78563cd0ce438beb8c1fbd57a92edfa6b00dcb0/sites/all/modules/custom/bgpage/bgpage.ds.field.inc#L223

**Comment by kleintom** [comment]
If I remember correctly we used to just see an empty box at https://beta.bugguide.net/node/1954, now we're seeing images with broken image links:
![image](https://user-images.githubusercontent.com/632915/142345401-e90b8d97-e969-4ec1-b7bf-f9cdcbc7f0c9.png)

As far as I can tell this bug is fixed for me in a local build, just not on beta.

I haven't looked into this or thought about it much, but wild guess: current BugGuide uses base in combination with nid in a different way than we do now, a la this change: https://github.com/kleintom/bugguide/commit/40ecd407c37e888a5feb77f9240878b69ba5465b (At the moment it's not clear to me why more images aren't broken if that's the issue.) See also #417 which suggests (well, sometimes it does, sometime it doesn't!) that using the old 'base + nid' obfuscation would work on migrated images on beta, i.e. that if we reverted that commit we might see the representative images on beta [though that's not the fix we want].

**Comment by kleintom** [comment]
Hmm, wonder if more isn't broken because it looks like migrated images are being saved/attached to their migrated node using the old obfuscate(base + nid) (I think that's what's going on?) https://github.com/bugguide/bugguide/blob/95c871c1be2d4bfe4b3376e8d7d31750f0dc4e92/sites/all/modules/custom/bgmigrate/lib/BGImageFieldMigration.inc#L124-L130

**Comment by kleintom** [comment]
I think this issue is actually fixed now: representative images are showing up on guide pages; created 420 to address the fact that their links are broken (for migrated images).

**Comment by kleintom** [comment]
Manual representative images are now showing on beta: 
![image](https://user-images.githubusercontent.com/632915/146649068-5ce791aa-267e-46ed-b0e0-8fd6be151394.png)
