### ISSUE TITLE
Validate nonblank custom license

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#321]
In #305 there were some issues with custom license display.

We would much rather that people choose one of the existing, standard licenses for their images.

But we still provide the ability to have a custom license if people want one (or have their own lawyer...).

Only in the case that people choose a custom license from the radio selections in Contributed Content License Terms, we cannot have the Additional license information field left blank.

This issue is to validate that it is not left blank. One way, and probably the easiest, to do that would be to check in form validation; the other way would be to make the additional license field required when Custom is chosen, since Drupal will automatically validate required fields.

**Comment by kleintom** [comment]
Working on beta - if you select 'custom license' in your user settings, it won't validate unless you also enter something for 'Additional license information'. (When it fails to validate you get a red box around the 'Additional license information' box, as expected; your text also turns red when you enter text in that box, which personally I find a little much, but I guess it's the Drupal way: the same thing happens if you try to save an empty comment.)
